### PR TITLE
arm64 kernel shrink

### PR DESCRIPTION
**Pull request by jepio**
# arm64 kernel shrink

Disable some unneeded kconfig options and turn wireguard into a module. This shrinks the arm64 kernel by ~3MB based on my testing.

## How to use

Check image changes to see size decrease. Check kola to see that wireguard continues to work without manually loading module.

## Testing done

Build tested.

- [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by jepio** [comment]
CI here: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/573/cldsv/

**Comment by pothos** [comment]
Makes sense for now, thanks! In the future it would be nice to support more boards, though - I'm looking forward to Linux 6.1 to enable generic EFI compression.

**Comment by pothos** [comment]
A changelog entry would be good

**Review by dongsupark — APPROVED** [review]
If I understand correctly, we need to merge this PR before https://github.com/flatcar/coreos-overlay/pull/2235, not to exceed the 60MB limit of arm64 Kernel, right?
Please add a proper changelog as Kai said, and feel free to merge.

**Comment by jepio** [comment]
> If I understand correctly, we need to merge this PR before https://github.com/flatcar/coreos-overlay/pull/2235, not to exceed the 60MB limit of arm64 Kernel, right?

We're at 59 MB with that PR (and some recent ones) merged, so yeah, it's necessary to merge this one.

Added changelog entries and merging.

**Pull request merged**
