### PR TITLE
dev-libs/openssl: Bump to 3.0.7

### PR DESCRIPTION
**Pull request by krnowak**
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/365/cldsv

- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [x] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by krnowak** [comment]
CI passed.

**Review by dongsupark — APPROVED** [review]

**Comment by dongsupark** [comment]
Maybe cherry-pick to flatcar-3227(current Stable), flatcar-3346(next Stable), flatcar-3374(Beta), flatcar-3402(Alpha)?

**Comment by krnowak** [comment]
Sure.

**Comment by krnowak** [comment]
Hm, 3346 is going to be next stable? Not 3374?

**Comment by dongsupark** [comment]
Yes, 3346.2.0 Stable according to https://github.com/orgs/flatcar/projects/7/views/8, unless @sayanchowdhury had other thoughts.

**Comment by krnowak** [comment]
Meh, that complicates things, because I wasn't backporting anything to branches that were not denoted as stable, alpha, beta or LTS. For me, flatcar-3346 is a dead branch now.

**Comment by dongsupark** [comment]
As discussed, the next Stable will be 3374.2.0.

**Comment by krnowak** [comment]
Pushed to alpha, beta and stable. LTS is still on openssl 1.1.1, so needs a separate PR.

**Comment by krnowak** [comment]
LTS wasn't affected by the CVEs apparently, so not critical to update yet.

**Pull request merged**
