### PR TITLE
update sys-apps/shadow to 4.13

### PR DESCRIPTION
**Pull request by jepio**
# update shadow to 4.13 
Update sys-apps/shadow to 4.13 which is marked stable in Gentoo and contains a bugfix for flatcar/Flatcar#904

## How to use

`emerge-amd64-usr shadow`

## Testing done

None, need to run CI.

- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by jepio** [comment]
http://192.168.42.7:8080/job/container/job/packages_all_arches/1077/cldsv/

**Comment by dongsupark** [comment]
CI passed, looks good in general.

For some reason, however, commits have the author `jenkins <jenkins@localhost.local>`.

**Comment by jepio** [comment]
My bad - let me fix that and add a changelog.

**Comment by jepio** [comment]
Also - what do you think about pushing to beta and/or stable? Since it fixes #904.

**Comment by dongsupark** [comment]
> Also - what do you think about pushing to beta and/or stable? Since it fixes https://github.com/flatcar/coreos-overlay/pull/904.

I think you mean https://github.com/flatcar/Flatcar/issues/904.

As shadow [4.13](https://github.com/shadow-maint/shadow/releases/tag/4.13) seems to have a fair amount of changes since 4.12, I am not sure if the backport to Stable/Beta would be a good idea.

**Comment by jepio** [comment]
> > Also - what do you think about pushing to beta and/or stable? Since it fixes #904.
> 
> I think you mean [flatcar/Flatcar#904](https://github.com/flatcar/Flatcar/issues/904).
> 
> As shadow [4.13](https://github.com/shadow-maint/shadow/releases/tag/4.13) seems to have a fair amount of changes since 4.12, I am not sure if the backport to Stable/Beta would be a good idea.

Alright. Commit author is fixed and I added a changelog

**Review by dongsupark — APPROVED** [review]

**Pull request merged**
