### PR TITLE
Bump kernel to 6.1

### PR DESCRIPTION
**Pull request by krnowak**
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1343/cldsv

- [ ] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)
- [ ] Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc.

### CODE REVIEW

**Comment by pothos** [comment]
Thanks for picking this up! Since we have to mess with kernel configs now it would be nice to see if we can also enable `CONFIG_EFI_ZBOOT` for arm64 – not sure if that works well with GRUB and (i)PXE but normally it should. That's for a separate commit/PR because we might have to revert it.

**Comment by pothos** [comment]
Not sure why your linked build failed for amd64 but for arm64 it failed with this here:
```
  *   Requested options not enabled in build:
  *     CONFIG_ARCH_BCM2835
  *     CONFIG_ARCH_BCM_IPROC
  *     CONFIG_ARM64_CRYPTO
```
From a quick look I don't get what they want to have enabled in addition to what we have, I think we need to do some manual interaction with the build menu.

**Comment by krnowak** [comment]
> Not sure why your linked build failed for amd64 but for arm64 it failed with this here:
> 
> ```
>   *   Requested options not enabled in build:
>   *     CONFIG_ARCH_BCM2835
>   *     CONFIG_ARCH_BCM_IPROC
>   *     CONFIG_ARM64_CRYPTO
> ```
> 
> From a quick look I don't get what they want to have enabled in addition to what we have, I think we need to do some manual interaction with the build menu.

No worries, will have a look at it. I already had to drop some configs for amd64, but haven't run arm64 builds locally.

**Comment by krnowak** [comment]
Getting boot failures:

```
[    0.595921] Run /init as init process
[    0.602095] BPF: 	 type_id=1704 bits_offset=1664
[    0.602499] BPF:  
[    0.602711] BPF: Invalid name
[    0.602999] BPF: 
[    0.603208] failed to validate module [qemu_fw_cfg] BTF: -22
[    0.618799] systemd[1]: systemd 252 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL -ACL +BLKID +CURL -ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE -TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
[    0.621149] systemd[1]: Detected virtualization kvm.
[    0.621678] systemd[1]: Detected architecture x86-64.
[    0.622111] systemd[1]: Running in initrd.
[    0.623037] systemd[1]: No hostname configured, using default hostname.
[    0.623597] systemd[1]: Hostname set to <localhost>.
[    0.624092] systemd[1]: Initializing machine ID from random generator.
[    0.687366] systemd[1]: Queued start job for default target initrd.target.
[    0.701293] systemd[1]: Started systemd-ask-password-console.path.
[    0.702334] systemd[1]: Reached target cryptsetup.target.
[    0.703005] systemd[1]: Reached target paths.target.
[    0.703618] systemd[1]: Reached target slices.target.
[    0.704241] systemd[1]: Reached target swap.target.
[    0.704864] systemd[1]: Reached target timers.target.
[    0.705535] systemd[1]: Listening on iscsid.socket.
[    0.706179] systemd[1]: Listening on iscsiuio.socket.
[    0.706892] systemd[1]: Listening on systemd-journald-audit.socket.
[    0.707661] systemd[1]: Listening on systemd-journald-dev-log.socket.
[    0.708451] systemd[1]: Listening on systemd-journald.socket.
[    0.709203] systemd[1]: Listening on systemd-networkd.socket.
[    0.709955] systemd[1]: Listening on systemd-udevd-control.socket.
[    0.710716] systemd[1]: Listening on systemd-udevd-kernel.socket.
[    0.711425] systemd[1]: Reached target sockets.target.
[    0.722096] systemd[1]: Starting kmod-static-nodes.service...
[    0.722902] systemd[1]: Finished network-cleanup.service.
[    0.724089] systemd[1]: Starting systemd-fsck-usr.service...
[    0.725754] systemd[1]: Starting systemd-journald.service...
[    0.727054] systemd[1]: Starting systemd-modules-load.service...
[    0.728496] systemd[1]: Starting systemd-resolved.service...
[    0.729687] systemd[1]: Starting systemd-vconsole-setup.service...
[    0.730779] systemd[1]: Finished kmod-static-nodes.service.
[    0.731603] systemd[1]: Finished systemd-fsck-usr.service.
[    0.733818] systemd[1]: Starting systemd-tmpfiles-setup-dev.service...
[    0.739744] systemd[1]: Finished systemd-tmpfiles-setup-dev.service.
[    0.741624] BPF: 	 type_id=1330 bits_offset=256
[    0.741625] BPF:  
[    0.741626] BPF: Invalid name
[    0.741627] BPF: 
[    0.741628] failed to validate module [overlay] BTF: -22
[    0.760249] audit: type=1130 audit(1676393004.765:2): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-tmpfiles-setup-dev comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    0.760346] systemd[1]: Started systemd-journald.service.
[    0.762715] BPF: 	 type_id=1704 bits_offset=1664
[    0.762716] BPF:  
[    0.762717] BPF: Invalid name
[    0.762717] BPF: 
[    0.762718] failed to validate module [llc] BTF: -22
[    0.764614] audit: type=1130 audit(1676393004.769:3): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-journald comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    0.766795] audit: type=1130 audit(1676393004.771:4): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-resolved comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    0.769736] audit: type=1130 audit(1676393004.774:5): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-vconsole-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    0.796778] audit: type=1130 audit(1676393004.801:6): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-cmdline-ask comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    0.798896] BPF: 	 type_id=172 bits_offset=64
[    0.798897] BPF:  
[    0.798898] BPF: Invalid name
[    0.798898] BPF: 
[    0.798900] failed to validate module [scsi_mod] BTF: -22
[    0.827913] audit: type=1130 audit(1676393004.832:7): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-modules-load comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
[    0.844224] audit: type=1130 audit(1676393004.849:8): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-sysctl comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    0.860777] BPF: 	 type_id=172 bits_offset=64
[    0.861222] BPF:  
[    0.861434] BPF: Invalid name
[    0.861711] BPF: 
[    0.861932] failed to validate module [scsi_mod] BTF: -22
[    0.874493] dracut: FATAL: iscsiroot requested but kernel/initrd does not support iscsi
[    0.875185] dracut: Refusing to continue
```

I remember having the same problem on [one of the weekly updates](https://github.com/flatcar/portage-stable/pull/401#issuecomment-1381583824), but I don't know how this thing got fixed (I remember updating fixing ncompress, but I'm not sure if it was the culprit).

**Comment by krnowak** [comment]
Rebuilding to see if this is a flake. Maybe a result of this CET mismatch that Dongsu is now fixing, who knows.

**Comment by krnowak** [comment]
Will file a PR to scripts after Big Merge.

**Pull request closed without merging**
