### PR TITLE
changelog: Add an entry for go 1.18.7 update

### PR DESCRIPTION
**Pull request by krnowak**
Merged #2208, but forgot to add the security changelog.

### CODE REVIEW

**Comment by krnowak** [comment]
https://nvd.nist.gov/vuln/detail/ links didn't work for those CVEs, so used https://cve.mitre.org/cgi-bin/cvename.cgi ones instead.

**Review by dongsupark — APPROVED** [review]
Looks good.

FYI, you can continue writing NVD links, even when the CVEs are not available on NVD yet.
In some cases, the NVD links become available after many weeks or months.

**Comment by krnowak** [comment]
> Looks good.
> 
> FYI, you can continue writing NVD links, even when the CVEs are not available on NVD yet. In some cases, the NVD links become available after many weeks or months.

Ok, thanks for the hint. I'll use the NVD links next time.

**Comment by sayanchowdhury** [comment]
We mistakenly added the CVE to the `updates` folder instead of the `security` folder. We would need to keep this track in the future.

**Pull request merged**
